baseURL = 'https://cmoron.github.io/echauveau_hugo'
languageCode = 'fr'
title = 'Estelle Chauveau Homepage'

theme = "hugo-ttl"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
